# Use Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the application source code
COPY . .

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# Expose the necessary port
EXPOSE 50052

# Start the server
CMD ["python", "server.py"]