# Use Python base image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the application source code
COPY . .

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt

# Start the client
CMD ["python", "client.py"]